### ISSUE TITLE
add a rio-like table to detail new formats included

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/readepi#10]
Do all formats not included in `rio` are the same as the RDBMS?

If the list is not extensive, can be added in parentheses.

https://github.com/epiverse-trace/readepi/blob/35835223b127c3f29a17dd4d14cd51cef31a5fa0/README.Rmd#L41-L48

**Comment by Karim-Mane** [comment]
I cannot provide a list of file formats that be read by {readepi} and not by {rio} given that I don't know them in advance. 
We are anticipating that the function will be able to parse the file and detect separator between the columns in every other format than rio-covered.
If this is not possible, the function will raise an error and the user will be asked to provide a value for the `sep` argument.
