### ISSUE TITLE
vignette not running

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/readepi#11]
I could only access the vignette running locally its Rmd file

```
> browseVignettes("readepi")
No vignettes found by browseVignettes("readepi")
```

**Comment by Karim-Mane** [comment]
This happens when you don't use the option build_vignettes = TRUE

Have you tried installing with devtools::install_github("epiverse-trace/readepi@develop", build_vignettes = TRUE) ?

**Comment by avallecam** [comment]
Got it! I reinstalled it and now it works. Will this vignette be available on the [package website](https://epiverse-trace.github.io/readepi/)?

**Comment by Karim-Mane** [comment]
great - yes, in principle it will be available in the package website.
