### ISSUE TITLE
move .Rhistory to .gitignore

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/readepi#15]
To avoid committing the local changes of each contributor

https://github.com/epiverse-trace/readepi/blob/f83c6c178b5d0ebd4cf3e303fe0627f39aafeb28/.Rhistory

**Comment by avallecam** [comment]
as in the package template https://github.com/epiverse-trace/packagetemplate/blob/main/.gitignore

**Comment by avallecam** [comment]
and probably also remove it from the git history due to the large diffs?

**Comment by Karim-Mane** [comment]
done
