### ISSUE TITLE
replace `data` with `dat` in documentation

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/readepi#16]
While creating a reprex, I got the default output from the `data` object (which is a base function) when the testing code I wrote returned an error and did not overlap the `data` object with new content to print. For example:

``` r
library(readepi)
data <- readepi(...)
#> Error in ...
data
#> function (..., list = character(), package = NULL, lib.loc = NULL,
#> 	verbose = getOption("verbose"), envir = .GlobalEnv, overwrite = TRUE)
#> {
#> ...
```

<sup>Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

From the [style syntax chapter](https://style.tidyverse.org/syntax.html#object-names) there is this recommendation at the end: "Where possible, avoid re-using names of common functions and variables. This will cause confusion for the readers of your code."

This mostly is the responsibility of the users, but the objects used could drive that issue.

I gather the alternative of `dat` from [episoap code](https://github.com/epiverse-trace/episoap/blob/a913d79de848c51758f5f5fbf901f119af093521/inst/rmarkdown/templates/transmissibility/skeleton/skeleton.Rmd#L297)

**Comment by Karim-Mane** [comment]
This is accounted for
