### ISSUE TITLE
Interoperability with linelist

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/readepi#2]
For case investigation data files (e.g. in standard format from Go.Data API – https://epirhandbook.com/en/contact-tracing-1.html), need to check these can go straight into `linelist` once imported into R. Otherwise will need a function that can ensure data standardisation.

**Comment by Karim-Mane** [comment]
This is related to the issue #9 in {cleanepi}. Will be discussed and fixed in relation to that.
